name: lighthouse-check
on:
  push:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing packages
      run: npm install -g lighthouse
      
    - name: Installing packages
      run: lighthouse https://airhorner.com/
