on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            # Hello ✅
            # Hello ✅
            # Hello ✅
            # Hello ✅
            # Hello ✅
          allow-repeats: false # This is the default
